In [2]:
import numpy as np

In [3]:
vetor = np.arange(0,10)

print(vetor)
print(vetor[7])
print(vetor[2:5])

[0 1 2 3 4 5 6 7 8 9]
7
[2 3 4]


In [4]:
matriz = np.array(([5,10,15],[20,25,30],[35,40,45]))

print(matriz)
print(matriz[1])
print(matriz[1][0])
print(matriz[1,0])
print(matriz[2,:])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[20 25 30]
20
20
[35 40 45]


In [5]:
print(vetor)
print(vetor>4)
print(vetor[vetor>4])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]


In [6]:
print( vetor + vetor )
print( vetor * vetor )

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In [7]:
print( np.sqrt(vetor) )
print( np.max(vetor) )

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
9


In [8]:
print( np.random.randn(5) )
print( np.linspace(0,100,10) )

[ 0.8256646   0.02466666  1.07635033 -0.25302667  0.80760038]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
